### PR TITLE
Added linearsearch in c++

### PR DESCRIPTION
**Pull request by HimangsKalita**

### CODE REVIEW

**Comment by harshit-sharma-gits** [comment]
Awesome work @HimangsKalita !
But can you rename your file to `linearsearch.cpp` ?

That would be awesome and up-to the Contributing guidelines we've provided in issue #13 and [CONTRIBUTING.md](https://github.com/DecodersCommunity/dsa-library/blob/main/CONTRIBUTING.md)

**Comment by HimangsKalita** [comment]
sure

**Comment by HimangsKalita** [comment]
file name changed could you please add "hactoberfest-accepted" while merging the pr

[DecodersCommunity/dsa-library@`8226cec` (#10)](https://github.com/DecodersCommunity/dsa-library/pull/10/commits/8226cec708ebab6d4800c3342d2753d8c997ce78)

**Review by harshit-sharma-gits — APPROVED** [review]
Looks good to me

**Pull request merged**
