### PR TITLE
Added Interploation Search In C

### PR DESCRIPTION
**Pull request by gaurang7goel**
#13 Issue
@harshit-sharma-gits  please check.

### CODE REVIEW

**Review by harshit-sharma-gits — CHANGES_REQUESTED** [review]
You might want to change the filename to `interpolationsearch.c`

**Comment by gaurang7goel** [comment]
ok ,sir.

**Comment by gaurang7goel** [comment]
Done @harshit-sharma-gits  please check.

**Review by harshit-sharma-gits — APPROVED** [review]
Looks good, approving!

**Comment by gaurang7goel** [comment]
Thank you sir.

**Pull request merged**
