### PR TITLE
Created Linked List.cpp

### PR DESCRIPTION
**Pull request by k6431494**
Issue #12

### CODE REVIEW

**Comment by harshit-sharma-gits** [comment]
There is discrepancy in where you have placed your `TOPOLOGICAL SEARCH.cpp`.
You should put it inside an appropriate folder.

Also, make sure that you are following the guidelines mentioned at #13 in naming the files

**Comment by k6431494** [comment]
> There is discrepancy in where you have placed your `TOPOLOGICAL SEARCH.cpp`. You should put it inside an appropriate folder.
> 
> Also, make sure that you are following the guidelines mentioned at #13 in naming the files

@harshit-sharma-gits Sir, my forked repository is not reopening.
Screenshot (190)

 So, can you please merge my contributions as i am unable to make changes in it.
pls check the attached screenshot.

**Comment by k6431494** [comment]
I Have edited the files as instructed.

**Review by harshit-sharma-gits — APPROVED** [review]
Looks good to me, approving!

**Pull request merged**
