### PR TITLE
added required changes

### PR DESCRIPTION
**Pull request by Pakhi-v**

### CODE REVIEW

**Comment by harshit-sharma-gits** [comment]
@Pakhi-v You are adding algorithms in Data Structures folder, and therefore it is invalid, Please place the files in the appropriate folder inside `./Algorithms/...`.
And make sure that your files follow the naming guidelines mentioned in #13

**Comment by Pakhi-v** [comment]
I haven't added algorithm. I have added data structure so it is in data structure folder

**Comment by harshit-sharma-gits** [comment]
As per my knowledge, Hashing and Sorting are **Algorithms**, not **Data Structures**. You might want to revisit this?

**Comment by Pakhi-v** [comment]
Yess i will revisit it.

**Comment by harshit-sharma-gits** [comment]
This can be closed now. I think you should not spam the PRs by creating multiple unnecessary branches.

**Pull request closed without merging**
