### PR TITLE
Create arrlen.cpp

### PR DESCRIPTION
**Pull request by zeolee01**

### CODE REVIEW

**Review by harshit-sharma-gits — CHANGES_REQUESTED** [review]
Remove spaces from file names like use arrlen.cpp

**Comment by zeolee01** [comment]
> Remove spaces from file names like use arrlen.cpp

done sir

**Comment by codeguyhp** [comment]
Rename the files too !!

**Comment by codeguyhp** [comment]
Better now !!

**Review by harshit-sharma-gits — APPROVED** [review]
Seems good , Approving !!

**Pull request merged**
